### ISSUE TITLE
Staleness report generator fails to parse some version strings

### ISSUE THREAD

**Issue by just4brown** [aws/sagemaker-distribution#177]
During the release for [v1.5.0](https://github.com/aws/sagemaker-distribution/pull/175) the staleness report generator threw an error

```
python ./src/main.py generate-staleness-report --target-patch-version 1.5.0
```
```
Traceback (most recent call last):
  File "/local/home/jubrownd/workplace/sagemaker-distribution/./src/main.py", line 413, in <module>
    parse_args(get_arg_parser())
  File "/local/home/jubrownd/workplace/sagemaker-distribution/./src/main.py", line 409, in parse_args
    args.func(args)
  File "/local/home/jubrownd/workplace/sagemaker-distribution/src/package_staleness.py", line 96, in generate_package_staleness_report
    _get_installed_package_versions_and_conda_versions(image_config, target_version_dir,
  File "/local/home/jubrownd/workplace/sagemaker-distribution/src/package_staleness.py", line 86, in _get_installed_package_versions_and_conda_versions
    _get_package_versions_in_upstream(target_packages_match_spec_out,
  File "/local/home/jubrownd/workplace/sagemaker-distribution/src/package_staleness.py", line 23, in _get_package_versions_in_upstream
    package_version = get_semver(package_version)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/jubrownd/workplace/sagemaker-distribution/src/utils.py", line 26, in get_semver
    version = Version.parse(version_str)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jubrownd/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/semver/version.py", line 646, in parse
    raise ValueError(f"{version} is not valid SemVer string")
ValueError: 0.27.0.post1 is not valid SemVer string
```

It appears a version string in the env.out files resolved by conda is not actually a valid SemVer string (according to the SemVer parser used in our tool). We'll need to investigate to understand the discrepancy.

In this case the full package/version that causes the issue is:
```
https://conda.anaconda.org/conda-forge/linux-64/uvicorn-0.27.0.post1-py310hff52083_0.conda#ef1c54f288f05c7a2d931c8ff3596a76
```

**Comment by claytonparnell** [comment]
So the issue here is we depend on semver versioning, but conda-forge uses different requirements (see https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers). This means that packages can use versions like 1.2.3.post1, 1.2.3.dev1 on conda-forge, which will fail semver.Version.parse(). We should make our version parsing more robust to account for these differences.
